config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, :controllers => { registrations: 'registrations' } 

  resources :reports 

  root 'reports#index'

  post '/reports(.:format)', to: 'reports#create', as: 'create_reports'

end

# My routes
#                  Prefix Verb   URI Pattern                    Controller#Action
#         new_user_session GET    /users/sign_in(.:format)       devise/sessions#new
#             user_session POST   /users/sign_in(.:format)       devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)      devise/sessions#destroy
#            user_password POST   /users/password(.:format)      devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)  devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format) devise/passwords#edit
#                          PATCH  /users/password(.:format)      devise/passwords#update
#                          PUT    /users/password(.:format)      devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)        registrations#cancel
#        user_registration POST   /users(.:format)               registrations#create
#    new_user_registration GET    /users/sign_up(.:format)       registrations#new
#   edit_user_registration GET    /users/edit(.:format)          registrations#edit
#                          PATCH  /users(.:format)               registrations#update
#                          PUT    /users(.:format)               registrations#update
#                          DELETE /users(.:format)               registrations#destroy
#                  reports GET    /reports(.:format)             reports#index
#                          POST   /reports(.:format)             reports#create
#               new_report GET    /reports/new(.:format)         reports#new
#              edit_report GET    /reports/:id/edit(.:format)    reports#edit
#                   report GET    /reports/:id(.:format)         reports#show
#                          PATCH  /reports/:id(.:format)         reports#update
#                          PUT    /reports/:id(.:format)         reports#update
#                          DELETE /reports/:id(.:format)         reports#destroy
#                     root GET    /                              reports#index
#           create_reports POST   /reports(.:format)             reports#create

app/models/report.rb
class Report < ActiveRecord::Base
	belongs_to :users

	validates :headline, :details, :presence => true
	validates :headline, :length => {:minimum => 2}
	validates :headline, :uniqueness => true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reports, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_action :authenticate_user
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def authenticate_user
  end


  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :img_url, :country, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :img_url, :country, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!

  def index
  	@reports = Report.all
  	@users = User.all
  end

  def show
  	@report = Report.find(params[:id])
    @users = User.all
  end

  def new
  	@report = Report.new

  end

  def create
    @report = Report.create(report_params)
    # @user = current_user
    @report.user_id = current_user.id

    # @users = User.all
    # @report.user_id << current_user
    if @report.save
      redirect_to reports_path, :notice => "Your report has been saved."
    else 
      render :new
    end
  end

  ################################# apparently "new" and "edit" are used to render the view,
  ################################# and "create" and "update" are used to touch the db

  # def create
  # 	@report = Report.new(report_params)
  # 	if @report.save
  # 		redirect_to reports_path, :notice => "Your report has been saved."
  # 	else 
  # 		render :new
  # 	end
  # end

  def edit
  	@report = Report.find(params[:id])
    if @report[:user_id] != current_user[:id]
  		redirect_to root_path
  	end

  end

  def update
  	@report = Report.find(params[:id])
  	if @report.update(report_params)
  		redirect_to reports_path, :notice => "Your report has been updated." 
  	else
  		render :edit
  	end
  end

  def destroy
  	@report = Report.find(params[:id])
  	
  	# redirect_to reports_path, :notice => "Your report has been deleted."
    if @report[:user_id] = current_user[:id]
      @report.destroy
      redirect_to reports_path, :notice => "Your report has been deleted."
    else
      redirect_to root_path
    end
  end

  private

  def belongs_to_user?
    scope.where(:id => record.id).exists?
  end

  def report_params
    params.require(:report).permit(:headline, :details, :location, :image, :contact_name, :contact_info, :date_listed)
  end

  def user_params
    params.require(:user).permit(:id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  def authenticate_user # don't know if I need this
  end

  def new
  end

end

app/controllers/users/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

	def index
		@users = User.all
	end

	def show
		# @user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReportApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav>
		<a href="/"><img src="../../logo.jpg"></a>
		<% if user_signed_in? %>
		  <span class="grey">Logged in as <%= current_user.first_name %> </span> 
		  <%= link_to "View all reports", reports_path %>
		  <%= link_to "New report", new_report_path %>
		  <%= link_to 'Profile', edit_user_registration_path %>
		  <%= link_to "Log out", destroy_user_session_path, method: :delete %>
		<% else %>
		  <%= link_to "Sign up", new_user_registration_path %>
		  <%= link_to "Log in", new_user_session_path  %>
		<% end %>
	</nav>

	<% if notice %>
	  <p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
	  <p class="alert alert-danger"><%= alert %></p>
	<% end %>

	<%= yield %>
	<div style="clear: both;"></div>

	<footer><img src="/../../logo.jpg"> &copy; 2015</footer>

</body>
</html>

app/views/reports/_form.html.erb
<%= form_for @report do |form| %>
    <p>Headline: <br/><%= form.text_field :headline, :class => 'border-black' %></p>
    <p>Details: <br/><%= form.text_area :details, :class => 'border-black' %></p>
    <p>Location: <br/><%= form.text_field :location, :class => 'border-black' %></p>
    <p>Upload photos, files, documents: <br/><%= form.text_field :image, :class => 'border-black' %></p>
    <p>Contact name or entity: <br/><%= form.text_field :contact_name, :class => 'border-black' %></p>
    <p>Contact information: <br/><%= form.text_field :contact_info, :class => 'border-black' %></p>
    <p>Today's date: <br/><%= form.text_field :date_listed, :class => 'border-black' %></p>
    <p><%= form.hidden_field :user_id, :value => current_user %></p>
    <%= form.submit "Submit report", :class => 'border-black' %>
    <br/>
    <br/>
    <a href="/reports" class="border-black" style="font-size: 11px; font-family:'Arial'">Cancel</a>
<% end %>

app/views/reports/edit.html.erb
<div class="container">
	<h1>Update report </h1>
	<h2><%= @report.headline %></h2>

	<%= render :partial => 'form' %>

</div>
<br/>
<br/>

app/views/reports/index.html.erb
<div class="container">
	<h1>Recent Reports</h1>

  	<% @reports.each do |report| %>
	<div class="report">
  		<h2><%= report.headline %></h2>
		<img src="<%= report.image %>" class="border-black report-image">
		<div class="report-info">
			<p><%= report.details %></p>
			<p><strong><%= report.location %></strong></p>
			<li>Contact <%= report.contact_name %></li>
			<li>Contact info: <%= report.contact_info %></li>
			<li>Last updated <%= report.date_listed %></li>
		</div>

		<br/>
		<div class="report-links">
	  	<%= link_to 'View this report', report_path(report.id), :class => 'border-grey' %>
		</div>
	</div>
  	<% end %>
  	
</div>
<br/>
<br/>

app/views/reports/new.html.erb
<div class="container">
	<h1>Report an illegal incursion on your land</h1>
	<p class="red-text">Reach support organizations and journalists<br/> directly by making this report. </p>
	<p></p>

	<%= form_for @report do |form| %>
	    <p>Headline: <br/><%= form.text_field :headline, :class => 'border-black' %></p>
	    <p>Details: <br/><%= form.text_area :details, :class => 'border-black' %></p>
	    <p>Location: <br/><%= form.text_field :location, :class => 'border-black' %></p>
	    <p>Upload photos, files, documents: <br/><%= form.text_field :image, :class => 'border-black' %></p>
	    <p>Contact name or entity: <br/><%= form.text_field :contact_name, :class => 'border-black' %></p>
	    <p>Contact information: <br/><%= form.text_field :contact_info, :class => 'border-black' %></p>
	    <p>Today's date: <br/><%= form.text_field :date_listed, :class => 'border-black' %></p>
	    <p><%= form.hidden_field :user_id, :value => current_user.id %></p>
	    <%= form.submit "Submit report", :class => 'border-black' %>
	    <br/>
	    <br/>
	    <a href="/reports" class="border-black" style="font-size: 11px; font-family:'Arial'">Cancel</a>
	<% end %>

</div>
<br/>
<br/>

app/views/reports/show.html.erb
<div class="container">
	<h1><%= @report.headline %></h1>
	<img src="<%= @report.image %>" class="border-black">
	<p> <%= @report.details %></p>
	<p><strong><%= @report.location %></strong></p>
	<li>Contact <%= @report.contact_name %></li>
	<li>Contact info: <%= @report.contact_info %></li>
	<li>Last updated <%= @report.date_listed %></li>

	<div class="report-links">

		<%= link_to 'Update this report', edit_report_path, :class => 'border-grey' %>
	  	<%= link_to 'Delete this report', report_path, :method => 'delete', :class => 'border-grey', :confirm => "Are you sure you want to delete this report?" %>
  	</div>
  	<br/>
  	
</div>
<br/>
<br/>